# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimbinganProposal',
            fields=[
                ('bimbingan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Bimbingan')),
            ],
            bases=('base.bimbingan',),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100, unique=True)),
                ('ringkasan', models.CharField(max_length=5000)),
                ('keyword', models.CharField(max_length=100)),
                ('dospem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Dosen')),
                ('mhs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Mahasiswa')),
            ],
        ),
        migrations.AddField(
            model_name='bimbinganproposal',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proposal.Proposal'),
        ),
    ]
