# Generated by Django 2.0 on 2017-12-21 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimbinganProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('hasil', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField(max_length=500, unique=True)),
                ('katakunci', models.TextField(max_length=500)),
                ('ringkasan', models.TextField(max_length=1000)),
                ('akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mhsAkun', to=settings.AUTH_USER_MODEL)),
                ('dospem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Dosen')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileProposal', models.FileField(upload_to='')),
                ('masabimbingan', models.BooleanField()),
                ('tanggal', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('tempat', models.CharField(blank=True, max_length=30)),
                ('dospemsetuju', models.BooleanField(default=False)),
                ('penguji1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='penguji1', to='base.Dosen')),
                ('penguji2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='penguji2', to='base.Dosen')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propSid', to='proposal.Proposal')),
            ],
        ),
        migrations.AddField(
            model_name='bimbinganproposal',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propID', to='proposal.Proposal'),
        ),
    ]
