# Generated by Django 2.0 on 2017-12-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='lolos',
            field=models.BooleanField(default=False),
        ),
    ]
