# Generated by Django 2.0 on 2017-12-19 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171219_0929'),
        ('proposal', '0002_auto_20171219_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('dospem', models.BooleanField(default=False)),
                ('tempat', models.CharField(max_length=30)),
                ('fileProposal', models.FileField(upload_to='')),
                ('penguji1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penguji1', to='base.Dosen')),
                ('penguji2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penguji2', to='base.Dosen')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propSid', to='proposal.Proposal')),
            ],
        ),
        migrations.RemoveField(
            model_name='sidang',
            name='proposal',
        ),
        migrations.AlterField(
            model_name='bimbinganproposal',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propID', to='proposal.Proposal'),
        ),
        migrations.DeleteModel(
            name='Sidang',
        ),
    ]
