# Generated by Django 2.0 on 2017-12-21 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20171221_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarproposal',
            name='penguji1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penguji1', to='base.Dosen'),
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='penguji2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penguji2', to='base.Dosen'),
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='tanggal',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='tempat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
