# Generated by Django 2.0 on 2017-12-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_auto_20171221_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarproposal',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propSid', to='proposal.Proposal'),
        ),
    ]
