# Generated by Django 2.0 on 2017-12-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_auto_20171223_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminarproposal',
            name='id',
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='proposal',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='propSid', serialize=False, to='proposal.Proposal'),
        ),
    ]
