# Generated by Django 2.0 on 2017-12-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20171223_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarproposal',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='proposal',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='propSid', to='proposal.Proposal'),
        ),
    ]
