# Generated by Django 2.0 on 2017-12-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0009_auto_20171224_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimbinganproposal',
            name='proposal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='propID', to='proposal.Proposal'),
        ),
    ]
