# Generated by Django 2.0 on 2017-12-19 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=10, unique=True)),
                ('gelar', models.CharField(max_length=25)),
                ('akunDsn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='akunDsn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=14, unique=True)),
                ('akunMhs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='akunMhs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
