# Generated by Django 2.0 on 2017-12-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=150, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='id',
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='npm',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('akunDsn', models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.User')),
                ('nama', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=10, unique=True)),
            ],
            bases=('base.user',),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='akunMhs',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.User'),
        ),
    ]
