# Generated by Django 2.0 on 2017-12-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='nama',
        ),
    ]
