# Generated by Django 2.0 on 2017-12-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171219_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='posisi',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
