# Generated by Django 2.0 on 2017-12-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20171216_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='akunDsn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='akunDsn', to='base.User'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='akunMhs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='akunMhs', to='base.User'),
        ),
    ]
